### PR TITLE
Lithuanian was added

### PR DESCRIPTION
**Pull request by estim**
Lithuanian language was added, Russian language was fixed (setting inside mo/po files were wrong)

### CODE REVIEW

**Comment by philiparthurmoore** [comment]
Thank you! Do you have a WordPress.org username?

**Comment by philiparthurmoore** [comment]
@estim: Checking in with you. What's your .org username?

**Comment by estim** [comment]
Sorry for the delay.
It is "cannotdance"

2015-10-30 13:16 GMT+02:00 Philip Arthur Moore <notifications@github.com>:

**Comment by philiparthurmoore** [comment]
Thanks! I'll take care of this during the weekend.

**Pull request merged**
